[package]
name = "opscan"
version = "0.1.0"
edition = "2018"
authors = ["raakhul"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pnet = "0.28.0"
structopt = "0.3.23"
rayon = "1.0"
cidr = "0.2.0"

[profile.release]
opt-level = "z"